version: '3'

services:
  node:
    build: ./containers/node
    volumes:
      - ./mnt/wrap-node/node:/mnt
      - node_node_modules:/mnt/vsc-site/node_modules # for svelte
    tty: true
    ports:
      - '5173:5173' # for npm run dev
      - '4173:4173' # for npm run preview
      - '6006:6006'
    working_dir: /mnt
  e2e:
    image: mcr.microsoft.com/playwright:v1.31.2-focal
    environment:
      - DISPLAY=${_DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./mnt/wrap-node:/mnt
      - warap-node__node_modules:/mnt/node_modules
    tty: true

volumes:
  node_node_modules:
  warap-node__node_modules:
